name: deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 20.224.45.105
          port: 22
          username: cleopatra
          password: ${{secret.PASSWORD}}
          key: ${{secrets.PRIVATE_KEY}}
          script: "cd www; git pull origin main -f"
